# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image and push to Tenable.io CS
      inputs:
        containerRegistry: 'Tenable.io CS Cloud'
        repository: 'hello-world-python-azure-devops/hello-world-python'
        command: buildAndPush
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
- stage: Assess
  displayName: Assess image security
  jobs:
  - job: Assess
    displayName: Assess
    steps:
    - task: InvokeRESTAPI@1
      inputs:
        connectionType: 'connectedServiceName'
        serviceConnection: 'Tenable.io API'
        method: 'POST'
        headers: |
          {
          "Accept":"application/json", 
          }
        urlSuffix: '?image=hello-world-python&repo=hello-world-python-azure-devops&tag=$(Build.BuildId)'
        waitForCompletion: 'false'