# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image and push to Tenable.io CS
      inputs:
        containerRegistry: 'Tenable.io CS Cloud'
        repository: 'hello-world-python-azure-devops/hello-world-python'
        command: buildAndPush
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
    - task: ShellScript@2
      inputs:
        scriptPath: tiocs-azure-check.sh
